Makefile.lab:
	@:

add:
	@bin/add.sh

build:
	@musical-patterns build "webpack --config webpack.prod.js"

publish:
	@bin/publish.sh

ship:
	@bin/ship.sh

snapshot:
	@bin/snapshot.sh

update:
	@bin/update.sh
