const BASE_DURATION: number = 3
const BASE_GAIN: number = 0.1

const SILENT: number = 0
const PLACEHOLDER_PITCH_TO_AVOID_NULL_POINTER_ISSUES: number = 1
const SEPARATION_FOR_NEIGHBORING_NOTES: number = 0.1

const HARMONIC_SHIFT: number = 0

export {
    BASE_DURATION,
    BASE_GAIN,
    PLACEHOLDER_PITCH_TO_AVOID_NULL_POINTER_ISSUES,
    SILENT,
    SEPARATION_FOR_NEIGHBORING_NOTES,
    HARMONIC_SHIFT,
}
