const C8_FOR_STEPWISE = 4186
const UMOWCHUWOWIEST_CROSSED_WITH_STEPWISE_BASE_PITCH = 139.56

const BASE_DURATION = 3
const BASE_GAIN = 0.1
const BASE_PITCH = UMOWCHUWOWIEST_CROSSED_WITH_STEPWISE_BASE_PITCH

export {
	BASE_DURATION,
    BASE_GAIN,
    BASE_PITCH,
}
